import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profpic from "../../public/images/profile/profpic.png";
import profpic1 from "../../public/images/profile/imgg.png";
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-5/12">
              <Image src={profpic1} alt="CodeBucks" className="w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              {/* <h1 className="text-5xl font-bold leading-tight">
                Building Scalable Applications With Code, Cloud & DevOps.
              </h1> */}
              <AnimatedText
                text="Building Scalable Applications With Code, Cloud & DevOps."
                className="!text-6xl !text-left"
              />
              <p className="my-3 text-base text-lg text-gray-900">
                I’m a final-year Software Engineering undergraduate and Full
                Stack Developer specializing in DevOps practices. I design,
                build, and deploy modern web applications using MERN, Docker,
                Kubernetes, and AWS-focusing on automation, scalability, and
                real-world impact.
              </p>
              <p className="!text-left self-start my-1 text-sm text-gray-600">
                Tech Stack: MERN • Docker • Kubernetes • AWS • Terraform •
                Jenkins
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                "
                  download={true}
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="dasun@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-5 bottom-8 inline-block w-24">
          <Image src={lightbulb} alt="img" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
